### ISSUE TITLE
[S.3] Read Pressure Sensors at 10 Hz

### ISSUE THREAD

**Issue by adib82302** [StevensRockSat-C/AIR#12]
Read MPRLS pressure sensors at 10 Hz during  full simulation to ensure proper operation

**Comment by nlundquist1** [comment]
Do timings, ensure the rate is at least 10 Hz

**Comment by ALEEF02** [comment]
Acceptance via runtime testing. 10 Hz is **Should**

**Comment by ALEEF02** [comment]
Currently sampling at ~30 Hz, as of 4-20-24
