### ISSUE TITLE
[S.5.A] Ensure Continuity of Acceleration Data Read in Python

### ISSUE THREAD

**Issue by ALEEF02** [StevensRockSat-C/AIR#18]
We know the data is valid in C, but we should check if it's valid in python as well.

- [ ] Find something to shake the accelerometer (should be consistent and somewhat fast)
- [ ] Record a continuous sample through the DAQHatWrapper
- [ ] Test in Matlab to see if there's a shift or jumps in the frequency

**Comment by nlundquist1** [comment]
Verified with https://github.com/StevensRockSat-C/sensor-tests/tree/c7720e03bbb5711d0c7b70486cb2b0f080f4c22d
![continuity over change in voltage](https://github.com/StevensRockSat-C/sensor-tests/blob/c7720e03bbb5711d0c7b70486cb2b0f080f4c22d/Accelerometer/ADXL1001/Test%20Data%20Analysis/proof%20of%20continuity.png)
