### ISSUE TITLE
[S.8] Read accelerometer in lowest noise mode

### ISSUE THREAD

**Issue by nlundquist1** [StevensRockSat-C/AIR#2]
Set the accelerometer to the lowest noise mode

- [ ] MatLab code must filter below 5 Hz and above 3200 Hz

**Comment by ALEEF02** [comment]
SCRAPING S.8! Not feasible and not required in [User Guidelines ](https://www.nasa.gov/wp-content/uploads/2022/09/rocksat-c-user-guide-2024-1.pdf)

**Comment by ALEEF02** [comment]
Won't be done with the deactivation of the vibration experiment
