### ISSUE TITLE
Infinite loop in connecting to RTC

### ISSUE THREAD

**Issue by nlundquist1** [StevensRockSat-C/AIR#21]
Change to time_try_rtc > timeMS() - 3000
Make for loop instead of while loop?

https://github.com/StevensRockSat-C/AIR/blob/0a1a47961b92c18618f5cf5f8b67c74ed9ce5182/pi/main.py#L311

**Comment by ALEEF02** [comment]
Fixed in https://github.com/StevensRockSat-C/AIR/commit/8988ec5fd3695a57e28cbc6a6f30c7ad6f19598c by @nlundquist1
