### ISSUE TITLE
[S.1.A] Make DAQHAT Wrapper

### ISSUE THREAD

**Issue by nlundquist1** [StevensRockSat-C/AIR#3]
Ensure data is in correct format and accurate

- [x] Return data in CSV format
- [x] Transform voltage into pressure (conversion in data sheet)
- [x] Set buffer and read for 6.4 KHz

**Comment by ALEEF02** [comment]
DAQ Hat continous buffer read example: https://github.com/mccdaq/daqhats/blob/master/examples/python/mcc128/continuous_scan.py
