### ISSUE TITLE
[S.1.B] Test Validity of Accelerometer at 6.4kHz

### ISSUE THREAD

**Issue by nlundquist1** [StevensRockSat-C/AIR#5]
- [x] Make sure the actual sampling rate is at 6.4kHz
- [ ] Run for 15 minutes continuously and ensure no samples are dropped

**Comment by ALEEF02** [comment]
DAQ Hat continous buffer read example: https://github.com/mccdaq/daqhats/blob/master/examples/python/mcc128/continuous_scan.py

**Comment by ALEEF02** [comment]
Won't be done with the deactivation of the vibration experiement
