### ISSUE TITLE
[S.1] Read 6 accelerometers at 6.4kHz

### ISSUE THREAD

**Issue by nlundquist1** [StevensRockSat-C/AIR#6]
Ensure data can be read accurately with no overflow/loss of data

**Comment by ALEEF02** [comment]
Dependent on #5

**Comment by ALEEF02** [comment]
Done with https://github.com/StevensRockSat-C/sensor-tests/blob/TestData/Accelerometer/ADXL1001/Test%20Data%20Analysis/2024-02-14_6accelerometersHandShaken_Spectrogram.PNG and https://github.com/StevensRockSat-C/sensor-tests/blob/TestData/Accelerometer/ADXL1001/Test%20Data%20Analysis/2024-02-14_6accelerometersHandShaken_PowerSpectrum.PNG
